(function(){finderGroup={};this.finderDestory=function(){for(var a in finderGroup)delete finderGroup[a]};var q=function(a,e,c){e=e||"controller";var b={},d={};d[e]=d[e]||{};d[e][c[0]]=c[1];b[a]=d;return b},r=new Class({Extends:Drag,start:function(a){this.parent(a)}});Finder=new Class({Implements:[Events],options:{selectName:"items[]"},detailStatus:{},initialize:function(a,e){$extend(this.options,e);this.id=a;this.initStaticView();this.initView();this.listContainer=this.list.getContainer();this.attachStaticEvents();
this.attachEvents();this.options.packet&&this.loadPacket()},initStaticView:function(){$each(["action","form","filter","search","tip","header","footer","pager","packet"],function(a){this[a]=$("finder-"+a+"-"+this.id)},this)},initView:function(){this.list=$("finder-list-"+this.id).store("visibility",true);this.tip=$("finder-tip-"+this.id)},isVisibile:function(){if(!this.list.retrieve)return false;return $chk(this.list.retrieve("visibility"))},attachStaticEvents:function(){var a=this;if(a.search){var e=
a.search.getElement("input[search]").addEvent("keypress",function(b){if(b.code===13){b.stop();if(!this.value.trim().length)a.filter.value="";b=a.form.retrieve("rowselected",[]);a.refresh(b.length&&!b.contains("_ALL_")&&!confirm(LANG_Finder.refresh_confirm))}});a.search.getElement(".finder-search-btn").addEvent("click",function(){e.fireEvent("keypress",{stop:$empty,code:13})})}a.action&&a.action.getElements("*[submit]").addEvent("click",function(b){b&&b.stop&&b.stop();var d=this.get("target");b=this.get("submit");
var g=a.form.retrieve("rowselected"),k=a.form.retrieve("_rowindex",$H());g=g[0]=="_ALL_"?g:[];!g.length&&k&&k.getValues().sort(function(i,n){return i.toInt()-n.toInt()}).each(function(i){g.push(k.keyOf(i))});var j=new Element("form"),l=document.createDocumentFragment(),m=false;g.each(function(i){var n=a.options.selectName;if(i=="_ALL_")m=n="isSelectedAll";l.appendChild(new Element("input",{type:"hidden",name:n,value:i}))});j.appendChild(l);var h=d,f={};if(d&&d.contains("::")){h=d.split("::")[0];f=
JSON.decode(d.split("::")[1]);if($type(f)!="object")f={}}if(!j.getFirst())return MessageBox.error(LANG_Finder.error);d=this.getProperty("confirm");if(!(d&&!window.confirm(d))){if(m){d=a.form.action.match(/\?([\s\S]+$)/);d=d[1]?d[1]:"";d=[d,a.form.toQueryString(),a.filter.value].join("&");j.adopt(d.toFormElements())}switch(h){case "refresh":W.page(b,$extend({data:j,method:"post",onComplete:a.refresh.bind(a)},f));break;case "command":new cmdrunner(actionurl,{onSuccess:a.refresh.bind(a)});break;case "dialog":new Dialog(b,
$extend({title:this.get("dialogtitle")||this.get("text"),ajaxoptions:{data:j,method:"post"},onClose:function(){a.unselectAll();a.refresh.call(a)}},f));break;case "_blank":b=j.set({action:b,name:h,target:"_blank",method:"post"}).inject(document.body);b.submit();b.remove.delay(1E3,b);break;default:W.page(b,$extend({data:j,method:"post"},f))}}});if(a.header){a.header.addEvent("click",function(b){var d=$(b.target);d.hasClass("orderable")||(d=d.getParent(".orderable"));if(d){d=["desc"==d.get("order")?
"asc":"desc",d.get("key")].link({"_finder[orderType]":String.type,"_finder[orderBy]":String.type});a.fillForm(d).refresh();b.stopPropagation()}});var c=function(){try{a.header.setStyles({width:a.listContainer.clientWidth-a.listContainer.getPatch().x})}catch(b){}};c();LAYOUT.content_main.addEvent("resizelayout",c);a.header.addEvent("dispose",function(){LAYOUT.content_main.removeEvent("resizelayout",c)})}},selectAll:function(){this.header.getElement(".sellist").set("checked",true).fireEvent("change");
this.tip.fireEvent("_update","selectedall").fireEvent("_show");this.form.retrieve("rowselected").empty().push("_ALL_")},unselectAll:function(){this.header.getElement(".sellist").set("checked",false).fireEvent("change");this.form.retrieve("rowselected").empty();this.form.retrieve("_rowindex",$H()).empty();this.tip.fireEvent("_hide")},selectFav:function(a){this.list.getElements("table tbody td:nth-child(first)").each(function(e){var c=e.getElement("input[type=checkbox]");e.getElement(".fav-star-on")?
c.set("checked",!a).fireEvent("change"):c.set("checked",!!a).fireEvent("change")})},selectunFav:function(){this.selectFav(true)},attachEvents:function(){var a=this,e=this.listContainer;a.list.retrieve("eventInfo",{});var c=a.form.retrieve("rowselected",[]);if(a.header){var b=a.header.getElement(".finder-header"),d=a.header.getElement(".finder-filter");b&&b.getElements("col").each(function(h,f){f=f.toInt();var i=f+1,n=b.getElement("td:nth-child("+i+")").getElement(".finder-col-resizer");n&&new r(h,
{modifiers:{x:"width",y:false},limit:{x:[35,1E3]},handle:n,onBeforeStart:function(o){o.store("lc",a.list.getElements("col")[f]);d&&o.store("fc",d.getElements("col")[f])},onDrag:function(o){a.header.hasClass("col-resizing")||a.header.addClass("col-resizing");var p=o.getStyle("width").toInt();$(o.retrieve("lc")).setStyle("width",p);d&&$(o.retrieve("fc")).setStyle("width",p);$(o).addClass("resizing");if(window.webkit){b.getElement("td:nth-child("+i+")").setStyle("width",p);a.list.getElement("td:nth-child("+
i+")").setStyle("width",p)}},onComplete:function(o){a.header.removeClass("col-resizing");$(o).removeClass("resizing");if(a.list.getElement("td:nth-child("+i+")")){var p=a.list.getElement("td:nth-child("+i+")").get("key");EventsRemote.post({events:q("finder_colset",a.options.object_name+"_"+a.options.finder_aliasname,[p,o.getStyle("width").toInt()])})}}})})}if(a.tip){a.tip.addEvents({_update:function(h,f){this.retrieve("arg:class","NULL")!=h&&$$(this.childNodes).hide();var i=this.getElement("."+h);
if(i){i.innerHTML=i.innerHTML.replace(/<em>([\s\S]*?)<\/em>/ig,function(){return"<em>"+f+"</em>"});i.setStyle("display","block")}this.store("arg:class",h);this.retrieve("tipclone")||this.store("tipclone",(new Element("div",{"class":"hide",html:"&nbsp;",styles:{height:this.offsetHeight}})).injectTop(e))},_show:function(){if(this.style.visibility=="hidden"){this.setStyle("visibility","visible");this.retrieve("tipclone").removeClass("hide")}},_hide:function(){if(this.style.visibility!="hidden"){this.setStyle("visibility",
"hidden");this.retrieve("tipclone").addClass("hide")}}});var g=c.length;if(g>1)g==a.tip.get("count").toInt()||c.contains("_ALL_")?a.tip.fireEvent("_update",["selectedall",g]).fireEvent("_show"):a.tip.fireEvent("_update",["selected",g]).fireEvent("_show")}a.list.addEvents({selectrow:function(h){h.getParent(".row").addClass("selected")},unselectrow:function(h){h.getParent(".row").removeClass("selected")}});var k=a.list.getElements(".sel");a.rowCount=k.length;if(a.header&&a.header.getElement(".sellist"))var j=
a.header.getElement(".sellist").addEvent("change",function(){k.set("checked",this.checked).fireEvent("change")});k.each(function(h){if(Browser.ie){h.addEvent("click",function(){this.fireEvent("change")});h.addEvent("focus",function(){this.blur()})}h.addEvent("change",function(){if(j){c[this.checked?"include":"erase"](this.value);var f=a.form.retrieve("_rowindex",$H());this.checked?f.set(this.value,this.get("rowindex")):f.erase(this.value)}else c.empty().push(this.value);if(!this.checked&&c.contains("_ALL_")){c.erase("_ALL_");
return a.unselectAll()}f=c.length;var i=0;if(f>1)if(f==a.tip.get("count").toInt()||c.contains("_ALL_"))a.tip.fireEvent("_update",["selectedall",f]).fireEvent("_show");else{a.tip.fireEvent("_update",["selected",f]);i=function(){$clear(i);if(!(c.length<2)){if(a.list.retrieve("eventState")=="mousedown")return i=arguments.callee.delay(200);a.tip.fireEvent("_show")}}.delay(200)}else{$clear(i);a.tip.fireEvent("_update",["selected"]);a.tip.fireEvent("_hide")}a.list.fireEvent(this.checked?"selectrow":"unselectrow",
this)});if(c&&c.push&&(c.contains(h.value)||c.contains("_ALL_")))h.set("checked",true).fireEvent("change");if(row=h.getParent(".row"))(h=row.get("item-id"))&&h==a.detailStatus.rowId&&a.showDetail(row.getElement("span[detail]").get("detail"),{},row)});a.list.addEvent("click",function(h){var f=$(h.target);if(f){if(f.match("img"))f=$(f.parentNode);if(f.hasClass("fav-star")){f.toggleClass("fav-star-on");return EventsRemote.post({events:q("finder_favstar",a.options.object_name+"_"+a.options.finder_aliasname,
["id-"+f.getParent("tr[item-id]").get("item-id"),f.hasClass("fav-star-on")?1:0])})}var i=f.get("detail");if(i){h.stopPropagation();return a.showDetail(i,{},f.getParent(".row"))}if(f.hasClass("cell")||f.hasClass("cell-inside"))f=f.getParent("td");if(f.match("td"))if(/row/.test(f.parentNode.className))if(a.detailStatus.row)if((h=f.getParent(".row").getElement("*[detail]"))&&!f.getParent(".row").hasClass("view-detail"))return a.showDetail(h.get("detail"),{},f.getParent(".row"))}});attachEsayCheck(a.list,
"td:nth-child(first) .span-auto");var l=0,m=function(){$clear(l);l=function(){if(this.listContainer.scrollLeft!=this.header.scrollLeft){var h=this.header.scrollLeft=this.listContainer.scrollLeft,f=this.listContainer.getElement(".finder-detail-content");f&&f.setStyle("margin-left",h)}this.tip&&this.tip.style.visibility!="none"&&this.tip.setStyles({left:this.listContainer.scrollLeft,top:this.listContainer.scrollTop})}.delay(200,this)}.bind(this);m();this.listContainer.addEvent("scroll",m);this.list.addEvent("dispose",
function(){this.listContainer.removeEvent("scroll",m)}.bind(this));this.cellOpts.call(this)},fillForm:function(a){if(!(!a||"object"!=$type(a))){a=$H(a);var e=this;a.each(function(c,b){(e.form.getElement("input[name^="+b.slice(0,-1)+"]")||(new Element("input",{type:"hidden",name:b})).inject(e.form)).set("value",c)});return e}},eraseSelected:function(){var a=this,e=a.form.retrieve("rowselected",[]);if(e[0]!="_ALL_"){var c=a.list.getElements(".sel");$splat(arguments).flatten().each(function(b){var d=
c.filter(function(g){return g.value==b});if(d.length)d.set("checked",false).fireEvent("change");else{e.erase(b);a.tip.fireEvent("_update",["selected",e.length])}})}},eraseFormElement:function(){var a=Array.flatten(arguments),e=this;$each(a,function(c){e.form.getElement("input[name="+c+"]").remove()});return e},showDetail:function(a,e,c){var b=this,d=c.getNext();e=c.get("item-id");if(this.detailCurTab&&this.detailCurTab[0]==e)a=this.detailCurTab[1];if(d&&d.hasClass("finder-detail"))return this.hideDetail(c,
d);this.hideDetail(this.detailStatus.row,this.detailStatus.dp);var g=new Element("tr",{"class":"finder-detail"}),k=new Element("td",{colspan:c.getElements("td").length,"class":"finder-detail-colspan"}),j=(new Element("div",{"class":"finder-detail-content clearfix",id:"finder-detail-"+this.id})).set({container:true});g.adopt(k.adopt(j));var l=this.list.getContainer();(d=this.detailStatus.Request)&&d.cancel();this.detailStatus.row=c.addClass("view-detail");this.detailStatus.rowId=e;this.detailStatus.Request=
(new Request.HTML({evalScripts:false,url:a+(a.indexOf("&")>0?"&":"")+"finder_name="+this.id,onRequest:function(){new MessageBox(LANG_Finder.detail.request,{type:"notice"})},onComplete:function(m,h,f,i){g.injectAfter(c);new MessageBox(LANG_Finder.detail.complete,{autohide:1});W.render(j.set("html",f));var n=function(){try{j.setStyle("width",l.clientWidth-k.getPatch().x)}catch(o){}};n();LAYOUT.content_main.addEvent("resizelayout",n);b.list.addEvent("dispose",function(){LAYOUT.content_main.removeEvent("resizelayout",
n)});$globalEval(i)}.bind(this),onFailure:function(){new MessageBox(LANG_Finder.detail.failure+[this.xhr.status],{type:"error",autohide:true})}})).send().chain(function(){delete this.detailStatus.Request;this.detailStatus.dp=g;l.retrieve("fxscroll",new Fx.Scroll(l,{link:"cancel"})).toElement(c)}.bind(this))},hideDetail:function(a,e){a&&a.removeClass("view-detail");e&&e.remove();delete this.detailCurTab;delete this.detail;delete this.detailStatus.row;delete this.detailStatus.dp;delete this.detailStatus.rowId},
getFormQueryString:function(){return this.form.toQueryString()},page:function(a){this.form.store("page",a||1);this.request({method:this.form.method||"post"})},loadPacket:function(){var a=this.packet;this.options.packet&&(new Request.HTML({url:this.form.action+"&action=packet",update:a,onRequest:function(){a.addClass("loading")},onComplete:function(){a.removeClass("loading")}})).get()},storeTab:function(){var a=$("finder-detail-"+this.id);if(a)if(a=a.getElement(".finder-tabs-wrap .current"))this.detailCurTab=
[a.get("item-id"),a.get("url")]},refresh:function(a){this.storeTab();this.request({method:this.form.method||"post",onComplete:function(){this.loadPacket();a&&this.unselectAll()}.bind(this)})},filter2packet:function(){var a=this.filter.value;a&&new Dialog(this.form.action+"&action=filter2packet",{width:400,height:200,ajaxoptions:{method:"post",data:$H({filterquery:a,finder_id:this.id})}})},setCount:function(){var a=this.tip.get("count").toInt(),e=$E(".finder-title .count");e&&e.setText(a);return this},
request:function(){var a=Array.flatten(arguments).link({options:Object.type,action:String.type});a.action=a.action||this.form.action+"&page="+(this.form.retrieve("page")||1);a.options=a.options||{};var e=a.options.onComplete;if($type(e)!="function")e=$empty;$extend(a.options,{clearUpdateMap:false,updateMap:{".innerheader":this.header,".pager":this.pager},onComplete:function(){this.initView();this.setCount().attachEvents();e.apply(this,Array.flatten(arguments));var d=$("filter-tip-"+this.id);if(d)this.filter.value.trim().length?
d.setStyle("visibility","visible").highlight("#FFFFCC"):d.setStyle("visibility","hidden")}.bind(this)});if(this.search&&this.search.getElement("input[search]").value.trim().length)this.filter.value=this.search.toQueryString();var c=this.getFormQueryString().concat("&"+this.filter.value),b=a.options.data;switch($type(b)){case "string":a.options.data=[c,b].join("&");break;case "object":case "hash":a.options.data=[c,Hash.toQueryString(b)].join("&");break;case "element":a.options.data=[c,$(b).toQueryString()].join("&");
break;default:a.options.data=c}for(v in this.detailStatus)$type(this.detailStatus[v])=="element"&&delete this.detailStatus[v];W.page(a.action,a.options)},cellOpts:function(){var a=this,e=a.list.getElements(".opt-handle");e&&e.each(function(c){var b=c.getSize().x,d=c.getPatch().x;new DropMenu(c,{eventType:"mouse",stopState:true,offset:{x:b-d-3,y:0},relative:$("main"),delay:0,size:true,onPosition:function(g){if(!this.offset)this.offset=this.options.offset.x;if(g=="x"){g=c.getParent("td").getSize().x;
g=b>g?g-d-12:this.offset;this.options.offset.x=this.options.relative.getScroll().x+g;this.options.offset.y=this.options.relative.getScroll().y}},onHide:function(){this.element.style.position="static"},onInitShow:function(){if(a.detailStatus.rowId)this.status=true},onShow:function(g){this.element.style.position="relative";if(!this.bind){g.getElements("a").addEvent("click",function(k){var j=this.get("submit")||this.get("url"),l=this.get("target");if(l&&j){k.preventDefault();k=l.split("::")[0]||l;var m=
JSON.decode(l.split("::")[1])||{};switch(k){case "dialog":var h=new Dialog(j,$extend(m,{onLoad:function(){this.dialog.getElement("form").store("target",{onComplete:function(){h.close();a.refresh()}})}}));break;case "tab":a.showDetail(j,m,this.getParent("tr"));break;case "request":(new Request({url:j,method:"post",data:m.data,onComplete:function(){a.showDetail(m.url,{},this.getParent("tr"))}.bind(this)})).send();break;case "confirm":if((l=this.get("confirm"))&&!confirm(l))break;W.page(j,{onComplete:function(){a.refresh()}})}}});
this.bind=true}}})})}});Filter=new Class({Implements:[Events,Options],options:{onPush:$empty,onRemove:$empty,onChange:$empty},initialize:function(a,e,c){this.finderId=e;this.filter=$(a);this.finderObj=window.finderGroup[e];this.setOptions(c)},update:function(){var a=this.filter,e=a.toQueryString(function(c){var b=$(c).getParent("dl");if(!(!b||!b.isDisplay()||!$(c).value)){if(b=c.name.match(/_([\s\S]+)_search/))if(!a.getElement("*[name="+b[1]+"]").value)return;if(c.name.match(/_DTYPE_TIME/))if(!a.getElement("*[name="+
c.value+"]").value)return;if(b=c.name.match(/_DTIME_\[([^\]]+)\]\[([^\]]+)\]/))if(!a.getElement("*[name="+b[2]+"]").value)return;return true}},true);if(this.finderObj.search)this.finderObj.search.getElement("input[search]").value="";this.finderObj.filter.value=e;e=this.finderObj.form.retrieve("rowselected",[]);this.finderObj.refresh(e.length&&!e.contains("_ALL_")&&!confirm(LANG_Finder.refresh_confirm));this.fireEvent("change")},retrieve:function(){var a=this.finderObj.filter.value||"";if(this.finderObj.search)this.finderObj.search.getElement("input[search]").value=
"";var e=this;a.replace(/([^&]+)\=([^&]+)/g,function(){var c=arguments,b=c[1],d=e.filter.getElement("[name="+b+"]");if(b&&b.slice(-1)&&b.slice(-1)=="]")d=e.filter.getElement("[name^="+b.substr(0,b.length-1)+"]");if(d)d.value=decodeURIComponent(c[2])})}})})();
(function(){var q=new Tips({onShow:function(c,b){b.addClass("active");var d;c.setStyle("display","block").store("tip:imgsource",d=$pick(b.get("href"),b.get("src")));var g=c.getElement(".tip-text").set("html","&nbsp;").addClass("loading");Asset.image(d,{onload:function(){if(this.src==c.retrieve("tip:imgsource")){g.empty().adopt(this.zoomImg(g.offsetWidth,g.offsetHeight)).removeClass("loading");this.setStyle("margin-top",(g.offsetHeight-this.height)/2)}}})},text:function(){return"&nbsp;"},className:"finder-col-img-tip"}),
r=new Tips({onShow:function(c,b){b.addClass("active");c.setStyle("display","block");var d=b.retrieve("loaded:html"),g=c.getElement(".tip-text");if(d)return g.set("html",d);g.set("html","&nbsp;").addClass("loading");(new Request({url:b.get("data-load"),onSuccess:function(k){g.removeClass("loading").empty().set("html",k);b.store("loaded:html",k)}})).get()},text:function(){return"&nbsp;"},className:"finder-col-desc-tip"}),a=new Tips({onShow:function(c,b){b.addClass("active");c.setStyle("display","block")},
text:function(c){return c.get("title")||c.get("rel")},className:"finder-col-text-tip"}),e=new Tips({onShow:function(c,b){b.addClass("active");c.setStyle("display","block")},text:function(c){return c.getElement("textarea").value},className:"finder-col-desc-tip"});this.bindFinderColTip=function(c){c=new Event(c);var b=c.target;if(b){b.onmouseover=null;if(b.hasClass("img-tip"))q.attach(b);else if(b.hasClass("desc-tip"))e.attach(b);else b.hasClass("load-tip")?r.attach(b):a.attach(b);b.addEvent("mouseleave",
function(){this.removeClass("active")});b.fireEvent("mouseenter",c)}}})();