var MessageBox=new Class({Implements:[Events,Options],options:{element:"messagebox",type:"default",autohide:false,type2class:{"default":"default",error:"exception",notice:"warning"}},initialize:function(b,a){this.setOptions(a);$clear(MessageBox.delay);this.options.element=$(this.options.element);for(e in this.options.element.$events)this.options.element.removeEvents(e);this.options.element.className=this.options.element.className.replace(/(default|warning|exception)/,"");this.options.element.set("html",
b);var c=this.options.autohide;if(c){c=$type(c)=="number"?c:3E3;MessageBox.delay=this.hide.delay(c,this)}return this.show()},show:function(){this.options.element.addClass(this.options.type2class[this.options.type]);return this.fireEvent("onShow",arguments)},hide:function(){this.options.element.removeClass(this.options.type2class[this.options.type]);return this.fireEvent("onHide",arguments)}});MessageBox.delay=0;
$extend(MessageBox,{error:function(b){new MessageBox(b,{type:"error",autohide:true})},success:function(b){new MessageBox(b,{autohide:true})},show:function(b){new MessageBox(b,{type:"notice",autohide:true})}});
(function(){var b,a,c=function(f){if(!f){if(undefined!=b)return b;return b=getTplById("dialog")}if(undefined!=a)return a;return a=getTplById("dialogwithframe")};Dialog=new Class({Implements:[Options,Events],options:{onShow:$empty,onHide:$empty,onClose:$empty,onLoad:$empty,callback:false,iframe:false,ajaksable:true,width:700,height:400,dialogBoxWidth:2,title:"",dragable:true,resizeable:true,singlon:true,modal:true,ajaxoptions:{update:false,evalScripts:true,method:"get",autoCancel:true,render:true}},
initialize:function(f,d){if(!(this.currentRegionDialogs=$$(".dialog")).some(function(g){if(g.retrieve("serial")==f.toString().trim()&&g.style.display!="none"){g.inject(document.body);return true}})){this.url=f;this.setOptions(d);d=this.options;var h=c(this.options.iframe);this.dialog=new Element("div",{id:"dialog_"+this.UID,"class":"dialog",styles:{visibility:"hidden",zoom:1,opacity:0,zIndex:65534}});this.UID=$uid(this.dialog);this.dialog.set("id","dialog_"+this.UID).setHTML(h).inject(document.body).store("serial",
f.toString().trim());this.options.callback&&this.dialog.store("callback",this.options.callback);this.dialog_head=$E(".dialog-head",this.dialog).addEvent("click",function(){$$(".dialog").length>1&&this.inject(document.body)}.bind(this.dialog));this.dialog_body=$E(".dialog-content-body",this.dialog);this.setTitle(d.title||"&nbsp;");$E(".btn-close",this.dialog_head).addEvents({click:function(g){g&&(new Event(g)).stop();this.close()}.bind(this),mousedown:function(g){(new Event(g)).stop()}});d.dragable&&
this.dragDialog();d.resizeable?this.dialog_body.makeResizable({handle:$E(".btn-resize",this.dialog),limit:{x:[200,window.getSize().x*0.9],y:[100,Math.max(window.getSize().y,window.getScrollSize().y)]},onDrag:function(){this.setDialogWidth()}.bind(this)}):$E(".btn-resize",this.dialog).hide();if(!d.ajaksable)d.ajaxoptions.render=false;$extend(d.ajaxoptions,{update:this.dialog_body,sponsor:false,resizeupdate:false,evalScripts:false,onRequest:function(){}.bind(this),onFailure:function(){this.close();
new MessageBox("\u5bf9\u8bdd\u6846\u52a0\u8f7d\u5931\u8d25",{type:"error",autohide:true})}.bind(this),onComplete:function(){this.fireEvent("onComplete",$splat(arguments));this.showDialog.attempt(arguments,this)}.bind(this)});this.popup(f,d)}},popup:function(f,d){this.fireEvent("onShow",this);this.initContent(f,d)},initContent:function(f,d,h){d=d||this.options;var g=this,j;if(!h){var i=arguments.callee;this.reload=function(){i(f,d,true)}}if(d.iframe){new MessageBox(LANG_Dialog.loading,{type:"notice"});
if(d.ajaxoptions.data){var k=d.ajaxoptions.data;switch(typeOf(k)){case "element":k=document.id(k).toQueryString();break;case "object":case "hash":k=Object.toQueryString(k)}j=new Element("form");j.adopt(k.toFormElements());j.set({id:"abbcc",action:f,method:d.ajaxoptions.method,target:this.dialog_body.name});j.injectAfter(this.dialog_body);return this.dialog_body.set("src","about:blank").addEvent("load",function(){g.showDialog.call(g,this);new MessageBox(LANG_Dialog.loading,{autohide:true});this.removeEvent("load",
arguments.callee);j.submit()})}return this.dialog_body.set("src",f).addEvent("load",function(){g.showDialog.call(g,this);new MessageBox(LANG_Dialog.success,{autohide:true});this.removeEvent("load",arguments.callee)})}if($type(f)=="element"){try{this.dialog_body.empty().adopt(f)}catch(m){this.dialog_body.setHTML(LANG_Dialog.error)}h||this.showDialog.call(this)}else W.page(f,d.ajaxoptions)},showDialog:function(f,d,h){(f=$E("*[isCloseDialogBtn]",this.dialog))&&f.addEvent("click",this.close.bind(this));
(f=$E("form[isCloseDialog]",this.dialog))&&f.store("target",{onComplete:function(g){if(g){var j={};try{j=JSON.decode(g)}catch(i){}g=j.finder_id;if(!j.error){this.close();g&&finderGroup[g]&&finderGroup[g].refresh()}}}.bind(this)});this.dialog.store("instance",this);this.setDialog_bodySize();(d=(f=this.currentRegionDialogs)?f.length:0)&&d>0?this.dialog.position($H(f[d-1].getPosition()).map(function(g){return g+20})).setOpacity(1):this.dialog.amongTo(window);this.options.modal&&MODALPANEL.show();$exec(h);
this.fireEvent("onLoad",this)},close:function(){try{this.fireEvent("onClose",this.dialog)}catch(f){}this.dialog.style.display="none";this.dialog.remove();$("dialogdragghost_"+this.UID)&&$("dialogdragghost_"+this.UID).remove();if(this.currentRegionDialogs.length>0)return false;this.options.modal&&MODALPANEL.hide();return"nodialog"},hide:function(){this.fireEvent("onHide");this.close.call(this)},setDialog_bodySize:function(){this.options.height=$type(this.options.height)=="string"?this.options.height.toInt():
this.options.height;this.options.width=$type(this.options.width)=="string"?this.options.width.toInt():this.options.width;var f=this.dialog.getElement(".dialog-content-head").getSize().y+this.dialog.getElement(".dialog-content-foot").getSize().y;this.dialog_body.setStyles({height:this.options.height<1?this.options.height*window.getSize().y-f:this.options.height-f,width:this.options.width<1?this.options.width*window.getSize().x:this.options.width});this.setDialogWidth()},setDialogWidth:function(){this.dialog.setStyle("width",
this.dialog_body.getSize().x+this.dialog.getElement(".dialog-box").getPatch().x)},setTitle:function(f){$E(".dialog-title",this.dialog_head).set("html",f)},dragDialog:function(){var f=this.dialog,d=new Element("div",{id:"dialogdragghost_"+this.UID});d.setStyles({position:"absolute",cursor:"move",background:"#66CCFF",display:"none",opacity:0.3,zIndex:65535}).inject(document.body);this.addEvent("load",function(){d.setStyles(f.getCis())});new Drag(d,{handle:this.dialog_head,limit:{x:[0,window.getSize().x],
y:[0,window.getSize().y]},onStart:function(){d.setStyles(f.getCis());d.show()},onComplete:function(){var h=d.getPosition();f.setStyles({top:h.y,left:h.x});d.hide()}})}})})();
var validatorMap=new Hash({required:[LANG_Validate.required,function(b,a){return a!=null&&a!=""&&a.trim()!=""}],number:[LANG_Validate.number,function(b,a){return a==null||a==""||!isNaN(a)&&!/^\s+$/.test(a)}],digits:[LANG_Validate.digits,function(b,a){return a==null||a==""||!/[^\d]/.test(a)}],unsignedint:[LANG_Validate.unsignedint,function(b,a){return a==null||a==""||!/[^\d]/.test(a)&&a>0}],unsigned:[LANG_Validate.unsigned,function(b,a){return a==null||a==""||!isNaN(a)&&!/^\s+$/.test(a)&&a>=0}],positive:[LANG_Validate.positive,
function(b,a){return a==null||a==""||!isNaN(a)&&!/^\s+$/.test(a)&&a>0}],alpha:[LANG_Validate.alpha,function(b,a){return a==null||a==""||/^[a-zA-Z]+$/.test(a)}],alphaint:[LANG_Validate.alphaint,function(b,a){return a==null||a==""||!/\W/.test(a)||/^[a-zA-Z0-9]+$/.test(a)}],alphanum:[LANG_Validate.alphanum,function(b,a){return a==null||a==""||!/\W/.test(a)||/^[\u4e00-\u9fa5a-zA-Z0-9]+$/.test(a)}],date:[LANG_Validate.date,function(b,a){return a==null||a==""||/^(19|20)[0-9]{2}-([1-9]|0[1-9]|1[012])-([1-9]|0[1-9]|[12][0-9]|3[01])$/.test(a)}],
email:[LANG_Validate.email,function(b,a){return a==null||a==""||/(\S)+[@]{1}(\S)+[.]{1}(\w)+/.test(a)}],url:[LANG_Validate.url,function(b,a){return a==null||a==""||/^(http|https|ftp):\/\/([A-Z0-9][A-Z0-9_-]*)(:(\d+))?\/?/i.test(a)}],area:[LANG_Validate.area,function(b){return b.getElements("select").every(function(a){var c=a.getValue();a.focus();return c!=""&&c!="_NULL_"})}],greater:[LANG_Validate.greater,function(b){var a=b.getPrevious("input[type=text]");return b.getValue()===""||b.getValue().toInt()>
a.getValue().toInt()}],requiredcheckbox:[LANG_Validate.requiredonly,function(b){var a=b.getParent();return(b.get("name")?a.getElements('input[type=checkbox][name="'+b.get("name")+'"]'):a.getElements("input[type=checkbox]")).some(function(c){return c.checked==true})}],requiredradio:[LANG_Validate.requiredonly,function(b){var a=b.getParent();return(b.get("name")?a.getElements('input[type=radio][name="'+b.get("name")+'"]'):a.getElements("input[type=radio]")).some(function(c){return c.checked==true})}]}),
validate=function(b){if(!b)return true;var a=false,c=(b.match("form")?b.getElements("[vtype]"):[b]).every(function(d){var h=d.get("vtype");if(!$chk(h))return true;if(!d.isDisplay()&&d.getAttribute("type")!="hidden")return true;var g=h.split("&&");if(d.get("required"))g=["required"].combine(g.clean());return h.split("&&").every(function(j){if(!validatorMap[j])return true;var i=d.getNext(".caution"),k=d.get("caution")||validatorMap[j][0];if(validatorMap[j][1](d,d.getValue())){i&&i.hasClass("error")&&
i.remove();return true}if(!i||!i.hasClass("caution")){(new Element("span",{"class":"error caution notice-inline",html:k})).injectAfter(d);d.removeEvents("blur").addEvent("blur",function(){if(validate(d)){i&&i.hasClass("error")&&i.remove();d.removeEvent("blur",arguments.callee)}})}else i&&i.hasClass("caution")&&i.get("html")!=k&&i.set("html",k);if(d.type!="hidden"&&d.isDisplay()&&!a)a=d;return false})});if(b.match("form")&&a)try{a.focus()}catch(f){}return c},HistoryManager=new Class({Implements:[Options,
Events],options:{observeDelay:100,stateSeparator:";",iframeSrc:"blank.html"},dataOptions:{skipDefaultMatch:true,defaults:[],regexpParams:""},initialize:function(b){if(this.modules)return this;this.setOptions(b);this.modules=$H({});this.count=history.length;this.states=[];this.states[this.count]=this.getHash();this.state=null;return this},start:function(){this.observe.periodical(this.options.observeDelay,this);this.started=true;this.observe();this.update();this.fireEvent("onStart",[this.state]);return this},
register:function(b,a,c,f,d,h){this.modules||this.initialize();a=$merge(this.dataOptions,h||{},{defaults:a,onMatch:c,onGenerate:f,regexp:d});a.regexp=a.regexp||b+"-([\\w_-]*)";if(typeof a.regexp=="string")a.regexp=RegExp(a.regexp,a.regexpParams);a.onGenerate=a.onGenerate||function(g){return b+"-"+g[0]};a.values=a.defaults.copy();this.modules.set(b,a);this.fireEvent("onUnregister",[b,a]);return{setValues:function(g){return this.setValues(b,g)}.bind(this),setValue:function(g,j){return this.setValue(b,
g,j)}.bind(this),generate:function(g){return this.generate(b,g)}.bind(this),unregister:function(){return this.unregister(b)}.bind(this)}},unregister:function(b){this.fireEvent("onRegister",[b]);this.modules.remove(b)},setValues:function(b,a){var c=this.modules.get(b);if(!c||c.values.isSimilar(a))return this;c.values=a;this.update();return this},setValue:function(b,a,c){b=this.modules.get(b);if(!b||b.values[a]==c)return this;b.values[a]=c;this.update();return this},generate:function(b,a){var c=this.modules.get(b),
f=c.values.copy();c.values=a;var d=this.generateState();c.values=f;return"#"+d},observe:function(){if(!this.timeout){var b=this.getState();if(this.state!=b){if(Browser.Engine.trident&&!document.querySelectorAll&&this.state!==null)this.setState(b,true);else this.state=b;this.modules.each(function(a){var c=b.match(a.regexp);if(c){c.splice(0,1);c.complement(a.defaults);if(!c.isSimilar(a.defaults))a.values=c}else a.values=a.defaults.copy();a.onMatch(a.values,a.defaults)});this.fireEvent("onStateChange",
[b]).fireEvent("onObserverChange",[b])}}},generateState:function(){var b=[];this.modules.each(function(a){a.skipDefaultMatch&&a.values.isSimilar(a.defaults)||b.push(a.onGenerate(a.values))});return b.join(this.options.stateSeparator)},update:function(){if(!this.started)return this;var b=this.generateState();if(!this.state&&!b||this.state==b)return this;this.setState(b);this.fireEvent("onStateChange",[b]).fireEvent("onUpdate",[b]);return this},observeTimeout:function(){this.timeout=this.timeout?$clear(this.timeout):
this.observeTimeout.delay(200,this)},getHash:function(){var b=self.location.href,a=b.indexOf("#")+1;return a?b.substr(a):""},getState:function(){var b=this.getHash();if(this.iframe){var a=this.iframe.contentWindow.document;if(a&&a.body.id=="state"){a=a.body.innerText;if(this.state==b)return a;this.istateOld=true}else return this.istate}return b},setState:function(b,a){b=$pick(b,"");self.location.hash=b||"#";if(Browser.Engine.trident&&!document.querySelectorAll&&(!a||this.istateOld)){if(!this.iframe){this.iframe=
(new Element("iframe",{src:this.options.iframeSrc,style:"visibility: hidden;height:1px;"})).injectInside(document.body);this.istate=this.state}try{var c=this.iframe.contentWindow.document;c.open();c.write('<html><body id="state">'+b+"</body></html>");c.close();this.istateOld=false}catch(f){}}this.state=b},extend:$extend});
Array.implement({isSimilar:function(b){return this.toString()==b.toString()},complement:function(b){for(var a=0,c=this.length;a<c;a++)this[a]=$pick(this[a],b[a]||null);return this},copy:function(b,a){b=b||0;if(b<0)b=this.length+b;a=a||this.length-b;for(var c=[],f=0;f<a;f++)c[f]=this[b++];return c}});
(function(){this.$globalEval=Browser.exec;var b=function(){$(document.body).addEvent("click",function(a){for(var c=$(a.target),f=0;f<3;f++)!c||$chk(c.get("href"))||(c=c.getParent());if(c&&c.get("href")){f=c.get("target")||"";var d=c.href||"";c.get("text");var h=!((!$chk(f)||f.match(/({|:)/))&&!d.match(/^javascript.+/i)&&!c.onclick),g=RegExp(""+SHOPADMINDIR+"");if(f.match(/blank/)&&d.match(g)){a.stop();return _open(d)}if(!h){a.stop();if(f.match(/::/)){var j=f.split("::");switch(j[0]){case "dialog":return new Dialog(d,
JSON.decode(j[1]||{}));case "open":return _open(d,JSON.decode(j[1]||{}));case "command":return Ex_Loader("cmdrunner",function(){(new cmdrunner(d,JSON.decode(j[1]||{}))).run()})}}if(a.shift)return open(d.replace("?","#"));W.page(d,$extend({method:"get"},JSON.decode(f)),c)}}})};this.Wpage=new Class({Extends:Request,exoptions:{evalScripts:true,link:"cancel",message:false,render:true,sponsor:false,clearUpdateMap:true,updateMap:{},url:"",data:"",headers:{"X-Requested-With":"XMLHttpRequest",Accept:"text/javascript, text/html, application/xml, text/xml, */*"},
async:true,format:false,method:"post",emulation:true,urlEncoded:true,encoding:"utf-8",evalResponse:false,noCache:false,update:false},initialize:function(a,c){a=$merge(this.exoptions,a);this.parent(a);b();if(!a.singlepage)if(typeof history.pushState!="undefined"){this.page("index.php?"+(location.hash.slice(1)?location.hash.slice(1):c));window.onpopstate=function(f){this.popstate=true;f.state&&this.page("index.php?"+f.state.go)}.bind(this)}else Ex_Loader("historyMan",function(){var f=new HistoryManager({iframeSrc:SHOPBASE+
"/app/desktop/view/blank.html"});this.hstMan=f.register("page",[c],function(d,h){return this.page("index.php?"+(d.input?d.input:h[0]))}.bind(this),function(d){return d[0]},".*");f.start()}.bind(this))},success:function(a,c){if(/text\/jcmd/.test(this.getHeader("Content-type")))return this.doCommand.apply(this,$splat(arguments));a=a.stripScripts(function(g){this.response.javascript=g}.bind(this));var f=a.match(/<body[^>]*>([\s\S]*?)<\/body>/i);if(f)a=f[1];f=this.options.update;var d=this.options.updateMap;
this.options.clearUpdateMap&&$H(d).each(function(g,j){!/side-/.test(j)&&g&&g.empty().fixEmpty()});a=a.replace(/<\!-{5}(.*?)-{5}([\s\S]*?)-{5}(.*?)-{5}>/g,function(g,j,i){g=j;g=d[g]||$(g);(i=i||null)&&g&&g.empty().set("html",i).fixEmpty();return""});f.empty().set("html",a);if(f==LAYOUT.content_main){var h=this.options.url.match("index\\.php\\?(.*)");if(h&&h[1])if(typeof history.pushState!="undefined"){history[this.popstate?"replaceState":"pushState"]({go:h[1]},"","#"+h[1]);this.popstate=false}else this.hstMan&&
this.hstMan.setValue(0,h[1])}this.render(f);this.options.evalScripts&&Browser.exec(this.response.javascript);this.onSuccess(a,c,this.response.javascript);this.onComplete()},onFailure:function(){switch(this.status){case 404:new MessageBox(LANG_Wpage.failure.status_404,{type:"error",autohide:true});break;case 401:new MessageBox(LANG_Wpage.failure.status_401,{type:"error"});break;case 403:new MessageBox(LANG_Wpage.failure.status_401,{type:"notice",autohide:true});break;default:new MessageBox(LANG_Wpage.failure.status+
this.status+"]",{type:"error",autohide:true})}this.parent()},doCommand:function(a,c){var f=this,d;if($type(a)=="string")try{d=JSON.decode(a)}catch(h){}else d=a;if(d&&$type(d)!="string"){d=$H(d);var g=d.getKeys(),j=d.getValues();return new MessageBox(j[0],{type:g[0]=="success"?"default":g[0],onHide:function(){if(g[0]=="error")return f.onSuccess(a,c)},onShow:function(){if(g[0]!="error"){if(!$chk(j[1]))return f.onSuccess(a,c);var i={},k;g[1]=="forward"&&$extend(i,{method:f.options.method,data:f.options.data});
f.onSuccess(a,c);(k=j[1].match(/javascript:([\s\S]+)/))?$globalEval(k[1]):f.page(j[1],i)}},autohide:d.autohide||1500})}else new MessageBox(a,{type:"notice",onHide:function(){f.onSuccess(a,c)},autohide:4E3})},eventClear:function(){for(e in this.$events)for(var a=this.$events[e].clean(),c=a.length;c--;)this.removeEvent(e,a[c]);return this},page:function(){var a=Array.flatten(arguments).link({url:String.type,options:Object.type,sponsor:Element.type});this.eventClear();var c=a.options&&a.options.update?
$(a.options.update):"";if(c)for(e in c.retrieve("events",{}))c.removeEvents(e);delete this.options.updateMap;a.options=a.options||{};this.setOptions(this.exoptions);a.options&&this.setOptions(a.options);if(a.sponsor)this.options.sponsor=a.sponsor;if(a.url)this.options.url=a.url;if(!this.options.update&&this.options.sponsor&&$type(this.options.sponsor)=="element")this.options.update=this.options.sponsor.getContainer();c=this.options.update=$(this.options.update||LAYOUT.content_main);a={".side-r-content":LAYOUT.side_r_content,
".mainHead":c.getPrevious(),".mainFoot":c.getNext(),".side-content":LAYOUT.side.getElement(".side-content")};this.options.updateMap=$merge(a,this.options.updateMap);this.setHeader("WORKGROUND",self.currentWorkground||"NULL");this.send(this.options);this.msgBox=new MessageBox(this.options.message||LANG_Wpage.loading,{type:"notice"})},render:function(a){if(!this.options.render)return this;a=a||this.options.update;var c=this;$(a).getElements("form").each(function(f){f.addEvent("submit",function(d){var h=
this;if(h.retrieve("submiting"))return d.stop();if(!validate(h)){d.stop();return new MessageBox(LANG_Wpage.form.error,{type:"error",autohide:true})}$ES("textarea[ishtml=true]",h).getValue();var g=h.get("target");if(g=="_blank")return true;if(h.get("enctype")=="multipart/form-data"||h.get("encoding")=="multipart/form-data"){h.target="upload";$("uploadframe").addEvent("load",function(){h&&h.uid&&h.eliminate("submiting");var i=this.contentWindow.document;i=i.body[i.body.innerText?"innerText":"textContent"];
var k=null;try{if((k=JSON.decode(i))&&k.splash)c.eventClear().doCommand.call(c,k)}catch(m){}var l=$(h).retrieve("target",{});if("onComplete"in l&&"function"==$type(l.onComplete))try{l.onComplete(i)}catch(n){}k||new MessageBox(LANG_Wpage.form.complete,{autohide:2E3});$("uploadframe").removeEvent("load",arguments.callee).set("src",$("uploadframe").retrieve("default:src"))}).store("default:src",$("uploadframe").src);h.store("submiting",true).submit();new MessageBox(LANG_Wpage.form.loading,{type:"notice"});
return true}d.stop();d=$merge(h.retrieve("target",{}),JSON.decode(g));var j=d.onComplete||$empty;d.onComplete=function(){j.apply(c,$splat(arguments));h&&h.uid&&h.eliminate("submiting")};c.page(h.store("submiting",true).action,$merge({method:h.method,data:h,message:LANG_Wpage.form.loading},d),h)})});console.log("W.render")},onComplete:function(){new MessageBox(LANG_Wpage.complete,{autohide:1E3});var a=this.options.update,c=$(a).getElements("input[date]");c&&c.length&&Ex_Loader("picker",function(){c.each(function(h){h.makeCalable()})});
if(BREADCRUMBS){var f=BREADCRUMBS.split(":");[LAYOUT.head,LAYOUT.side].clean().each(function(h){h.getElements(".current").removeClass("current");f.each(function(g){(g=h.getElement("a[mid="+g+"]"))&&g.addClass("current")})})}var d=$(a).getElements("input[autocompleter]");(d=$$(d,$(a).getElements("textarea[autocompleter]")))&&d.length&&Ex_Loader("autocompleter",function(){d.each(function(h){var g=h.get("autocompleter"),j="?app=desktop&ctl=autocomplete&params="+g;g=g.match(/:([^,]*)/)[1];h.addEvent("keydown",
function(i){i.code==13&&i.stop()});g=$merge({getVar:g,fxOptions:false,delay:300,callJSON:function(){return window.autocompleter_json},injectChoice:function(i){i=i[this.options.getVar];var k=new Element("li",{html:this.markQueryValue(i)});k.inputValue=i;this.addChoiceEvents(k).inject(this.choices)}},JSON.decode(h.get("ac_options")));new Autocompleter.script(h,j,g)})});console.log("W.complete")}})})();
var DropMenu=new Class({Implements:[Events,Options,LazyLoad],options:{onLoad:$empty,onShow:$empty,onHide:$empty,showMode:function(b){b.setStyle("display","block")},hideMode:function(b){b.setStyle("display","none")},dropClass:"droping",eventType:"click",relative:document.body,stopEl:false,stopState:false,lazyEventType:"show",delay:200,offset:{x:0,y:20}},initialize:function(b,a){if(this.element=$(b)){this.setOptions(a);var c=this.options.menu||this.element.get("dropmenu");(this.menu=$(c)||$E("."+c,
this.element.getParent()))&&this.load().attach()._lazyloadInit(this.menu)}},attach:function(){var b=this.options,a=b.stopState;b.eventType!="mouse"?this.element.addEvent("click",function(c){this.showTimer&&$clear(this.showTimer);a&&c.stop();this.showTimer=this.show().outMenu.delay(this.options.delay,this)}.bind(this)):$$(this.element,this.menu).addEvents({mouseenter:function(){this.show();this.timer&&$clear(this.timer)}.bind(this),mouseleave:function(){if(this.status)this.timer=this.hide.delay(this.options.delay,
this)}.bind(this)});this.menu.addEvent("click",function(c){if(true===b.stopEl)b.stopEl="stop";if(b.stopEl)return c[b.stopEl]();return this.hide()}.bind(this));return this},load:function(){return this.fireEvent("load",[this.element,this])},show:function(){this.fireEvent("initShow");if(this.status)return this;this.element.addClass(this.options.dropClass);this.options.showMode.call(this,this.menu);this.options.relative&&this.position({page:this.element.getPosition(this.options.relative)});this.status=
true;return this.fireEvent("show",this.menu)},hide:function(){this.options.hideMode.call(this,this.menu);this.element.removeClass(this.options.dropClass);this.status=false;this.fireEvent("hide",this.menu)},position:function(b){var a=this.options,c=$(a.relative),f=(c||window).getSize();c=(c||window).getScroll();var d={x:this.menu.offsetWidth,y:this.menu.offsetHeight};if(a.temppos){f=b.page.x+a.offset.x;return this.menu.setStyles({top:b.page.y+this.element.getSize().y+a.offset.y,left:f})}a={x:"left",
y:"top"};var h={},g;for(g in a){this.fireEvent("position",g);h[a[g]]=b.page[g]+this.options.offset[g];if(h[a[g]]+d[g]-c[g]>f[g]){var j=this.options.size?this.element.getSize()[g]:0;h[a[g]]=b.page[g]+this.options.offset[g]-d[g]+j}}this.menu.setStyles(h);return this},outMenu:function(){var b=this;document.body.addEvent("click",function(a){if(b.options.stopEl!=a.target&&b.menu){b.hide.call(b);$clear(b.showTimer);this.removeEvent("click",arguments.callee)}})}});